services:
  app_proxy:
    environment:
      APP_HOST: xec-web
      APP_PORT: 8080

  xec-web:
    image: ghcr.io/soggyhammydev/xec-solo-web:0.1.9
    restart: on-failure
    stop_grace_period: 5s
    depends_on:
      - xec-adapter

  xec-adapter:
    image: ghcr.io/soggyhammydev/xec-solo-adapter:0.1.9
    restart: on-failure
    stop_grace_period: 5s
    environment:
      PORT: "8081"
      XEC_RPC_HOST: xec-node
      XEC_RPC_PORT: "8332"
      XEC_RPC_USER: umbrel-xec
      XEC_RPC_PASSWORD: "${APP_SEED}"
      STRATUM_PORT: "3335"
      SETTINGS_FILE: /data/settings.json
      CKPOOL_HOST: xec-ckpool
      CKPOOL_PORT: "3333"
      CKPOOL_LOG_ROOT: /var/lib/ckpool/logs
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ckpool-runtime:/tmp/ckpool
      - ${APP_DATA_DIR}/ckpool:/var/lib/ckpool:ro
    depends_on:
      - xec-node
      - xec-ckpool
    networks:
      - default
      - xec-internal

  xec-ckpool:
    image: ghcr.io/soggyhammydev/xec-solo-ckpool:0.1.9
    restart: on-failure
    stop_grace_period: 10s
    environment:
      XEC_RPC_HOST: xec-node
      XEC_RPC_PORT: "8332"
      XEC_RPC_USER: umbrel-xec
      XEC_RPC_PASSWORD: "${APP_SEED}"
      SETTINGS_FILE: /data/settings.json
    ports:
      - "3335:3333"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/ckpool:/var/lib/ckpool
      - ckpool-runtime:/tmp/ckpool
    depends_on:
      - xec-node
    networks:
      - xec-internal

  xec-node:
    image: ghcr.io/soggyhammydev/xec-solo-node:0.1.9
    restart: on-failure
    stop_grace_period: 2m
    ports:
      - "8333:8333"
    environment:
      XEC_RPC_USER: umbrel-xec
      XEC_RPC_PASSWORD: "${APP_SEED}"
      XEC_RPC_PORT: "8332"
      SETTINGS_FILE: /settings/settings.json
    volumes:
      - ${APP_DATA_DIR}/node:/data
      - ${APP_DATA_DIR}/data:/settings:ro
    networks:
      - xec-internal

volumes:
  ckpool-runtime:

networks:
  xec-internal:
    driver: bridge
